"""add salesperson_id duration_seconds recorded_at to conversations

Revision ID: e272c0dd7159
Revises: 14cdd47b97b4
Create Date: 2026-06-10 03:56:08.670640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e272c0dd7159'
down_revision: Union[str, Sequence[str], None] = '14cdd47b97b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_analysis', sa.Column('loss_reason', sa.Text(), nullable=True))
    op.add_column('conversation_analysis', sa.Column('customer_expectation', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('salesperson_id', sa.Uuid(), nullable=True))
    op.add_column('conversations', sa.Column('duration_seconds', sa.Float(), nullable=True))
    op.add_column('conversations', sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_conversations_salesperson_id'), 'conversations', ['salesperson_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'salespeople', ['salesperson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_salesperson_id'), table_name='conversations')
    op.drop_column('conversations', 'recorded_at')
    op.drop_column('conversations', 'duration_seconds')
    op.drop_column('conversations', 'salesperson_id')
    op.drop_column('conversation_analysis', 'customer_expectation')
    op.drop_column('conversation_analysis', 'loss_reason')
    # ### end Alembic commands ###
